### ISSUE TITLE
NPE at ObservableRecyclerView.onScrollChanged()

### ISSUE THREAD

**Issue by boojtran** [ksoichiro/Android-ObservableScrollView#149]
Hi, 
First of all thanks for your awesome library, love it. I have a problem with ObservableRecyclerView. I have an activity (Activity A) like your ViewPagerTabActivity example, when I go back from another activity and switch tabs on A, it crashes.

```
Stack:
java.lang.NullPointerException
        at com.github.ksoichiro.android.observablescrollview.ObservableRecyclerView.onScrollChanged(ObservableRecyclerView.java:102)
        at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:3343)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2522)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2709)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4562)
        at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:562)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4562)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4562)
        at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1593)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4562)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4562)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4562)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4562)
        at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:907)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4562)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4562)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4562)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4562)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4562)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4562)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1976)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1730)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1004)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5481)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
        at android.view.Choreographer.doCallbacks(Choreographer.java:562)
        at android.view.Choreographer.doFrame(Choreographer.java:532)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
        at android.os.Handler.handleCallback(Handler.java:730)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5103)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:525)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
        at dalvik.system.NativeStart.main(Native Method)
```

Thanks for your help!

**Comment by ksoichiro** [comment]
@boojtran Thanks for your report.
I couldn't reproduce this problem, but I modified the codes to avoid NPE.
Could you test the fix?
This fix is released as 1.6.0-SNAPSHOT currently.

```gradle
repositories {
    mavenCentral()
    maven {
        url uri('https://oss.sonatype.org/content/repositories/snapshots/')
    }
}

dependencies {
    compile "com.github.ksoichiro:android-observablescrollview:1.6.0-SNAPSHOT"
}
```

**Comment by boojtran** [comment]
@ksoichiro Thanks for your support.
NPE doesn't happen any more, but I noticed that my list missing an item, I think that's why occur NPE.

**Comment by jkj8790** [comment]
It still occurs NPE on 1.6.0-SNAPSHOT version
When I start fragment that include ObservableRecyclerView and immediately scroll to bottom fast, it crashed.

if(this.mChildrenHeights.indexOfKey(firstVisibleChild) < 0 || child != null && child.getHeight() != this.mChildrenHeights.get(firstVisibleChild)) {
                    i = child.getHeight();
}

It doesn't guarantee that child is not null.
I’m not good at english, so if you don’t understand my word please tell me.

**Comment by ksoichiro** [comment]
@jkj8790 Sorry, I just fixed this in commit db593e3 yesterday, and updated the SNAPSHOT just now.

**Comment by jkj8790** [comment]
Thank you very much :) I'm using this library very useful!
